# Generated by Django 5.2.13 on 2026-04-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_company', models.CharField(blank=True, default='', max_length=255)),
                ('job_description', models.TextField()),
                ('tailored_skills', models.JSONField(default=list)),
                ('tailored_experience', models.JSONField(default=list)),
                ('tailored_education', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_versions', to='cv.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tailored_cvs',
                'ordering': ['-created_at'],
            },
        ),
    ]
