# Generated by Django 5.2.13 on 2026-04-27 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_add_tailoredcv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_company', models.CharField(blank=True, default='', max_length=255)),
                ('job_description', models.TextField()),
                ('body', models.TextField(help_text='Generated cover letter text (editable by user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='cv.cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cover_letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
