# Generated by Django 5.2.13 on 2026-05-01 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(max_length=1000)),
                ('job_title', models.CharField(max_length=500)),
                ('job_company', models.CharField(blank=True, default='', max_length=500)),
                ('job_location', models.CharField(blank=True, default='', max_length=500)),
                ('job_source', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('saved', 'Saved'), ('rejected', 'Rejected')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_interactions',
                'unique_together': {('user', 'job_url')},
            },
        ),
    ]
