# Generated by Django 5.2.13 on 2026-05-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_cached_job_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedjobsearch',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
