# Generated by Django 5.2.13 on 2026-04-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpreference',
            name='source_adzuna',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='source_arbeitnow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='source_hn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='source_remoteok',
            field=models.BooleanField(default=True),
        ),
    ]
