# Generated by Django 5.2.13 on 2026-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_jobpreference_source_adzuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpreference',
            name='digest_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='off', max_length=10),
        ),
    ]
