# Generated by Django 5.2.13 on 2026-05-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_jobpreference_digest_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpreference',
            name='source_adzuna',
        ),
    ]
